# Generated by Django 4.2.6 on 2023-11-04 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_companyinfo_rating'),
        ('core', '0002_alter_post_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='TendersList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenderNum', models.BigIntegerField()),
                ('tenderName', models.CharField(max_length=500)),
                ('tenderFormat', models.CharField(max_length=100)),
                ('tenderSumm', models.BigIntegerField()),
                ('srok', models.IntegerField()),
                ('organizationName', models.CharField(max_length=500)),
                ('organizationPhone', models.CharField(max_length=13)),
                ('organizationAddress', models.CharField(max_length=500)),
                ('dateTimeStart', models.DateTimeField()),
                ('dateTimeEnd', models.DateTimeField()),
                ('letterFile', models.URLField()),
                ('letterName', models.CharField(max_length=200, null=True)),
                ('lotsInfo', models.TextField(null=True)),
                ('moreInfo', models.URLField()),
                ('likes', models.PositiveIntegerField(default=0, null=True)),
                ('dislikes', models.PositiveIntegerField(default=0, null=True)),
                ('company_info', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tenders_list', to='companies.companyinfo')),
            ],
        ),
        migrations.CreateModel(
            name='ContractsList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenderNum', models.BigIntegerField()),
                ('tenderName', models.CharField(max_length=500)),
                ('organizationName', models.CharField(max_length=500)),
                ('winnerName', models.CharField(max_length=500)),
                ('dateContract', models.DateField()),
                ('contractNum', models.CharField(max_length=100)),
                ('lotsInfo', models.TextField()),
                ('pricesOnTender', models.TextField()),
                ('pricesOnContract', models.TextField()),
                ('totalPriceContract', models.BigIntegerField(null=True)),
                ('likes', models.PositiveIntegerField(default=0, null=True)),
                ('dislikes', models.PositiveIntegerField(default=0, null=True)),
                ('company_info', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contracts_list', to='companies.companyinfo')),
            ],
        ),
    ]
