# Generated by Django 4.2.6 on 2023-11-04 22:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_companyinfo_rating'),
        ('core', '0003_tenderslist_contractslist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenderslist',
            name='company_info',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tenders_list', to='companies.companyinfo'),
        ),
        migrations.AlterField(
            model_name='tenderslist',
            name='dateTimeEnd',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='tenderslist',
            name='letterFile',
            field=models.URLField(null=True),
        ),
    ]
