# Generated by Django 4.2.6 on 2023-11-05 01:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_companyinfo_rating'),
        ('core', '0004_alter_tenderslist_company_info_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contractslist',
            name='organizationName',
        ),
        migrations.AlterField(
            model_name='contractslist',
            name='company_info',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contracts_list', to='companies.companyinfo'),
        ),
    ]
