# Generated by Django 4.2.6 on 2023-11-05 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_contractslist_organizationname_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contractslist',
            name='totalPriceContract',
        ),
    ]
