# Generated by Django 4.2.6 on 2023-11-05 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_idea_delete_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Idea',
        ),
    ]
