# Generated by Django 4.2.6 on 2023-11-03 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TendersList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenderNum', models.BigIntegerField()),
                ('tenderName', models.CharField(max_length=500)),
                ('tenderFormat', models.CharField(max_length=100)),
                ('tenderSumm', models.BigIntegerField()),
                ('srok', models.IntegerField()),
                ('organizationName', models.CharField(max_length=500)),
                ('organizationPhone', models.CharField(max_length=13)),
                ('organizationAddress', models.CharField(max_length=500)),
                ('dateTimeStart', models.DateTimeField()),
                ('dateTimeEnd', models.DateTimeField()),
                ('srokGOPP', models.CharField(max_length=100)),
                ('letterFile', models.URLField()),
                ('lotNum', models.CharField(max_length=100)),
                ('lotName', models.CharField(max_length=500)),
                ('lotSum', models.BigIntegerField()),
                ('addressPostavki', models.CharField(max_length=500)),
                ('edIzmeren', models.CharField(max_length=100)),
                ('qty', models.IntegerField()),
                ('moreInfo', models.URLField()),
            ],
        ),
    ]
