# Generated by Django 4.2.6 on 2023-11-03 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenderslist',
            name='srokGOPP',
        ),
        migrations.AddField(
            model_name='tenderslist',
            name='letterName',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
