# Generated by Django 4.2.6 on 2023-11-03 14:43

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0002_remove_tenderslist_srokgopp_tenderslist_lettername'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenderslist',
            name='lotNum',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), size=None),
        ),
    ]
