# Generated by Django 4.2.6 on 2023-11-03 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0003_alter_tenderslist_lotnum'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenderslist',
            name='addressPostavki',
        ),
        migrations.RemoveField(
            model_name='tenderslist',
            name='edIzmeren',
        ),
        migrations.RemoveField(
            model_name='tenderslist',
            name='lotName',
        ),
        migrations.RemoveField(
            model_name='tenderslist',
            name='lotNum',
        ),
        migrations.RemoveField(
            model_name='tenderslist',
            name='lotSum',
        ),
        migrations.RemoveField(
            model_name='tenderslist',
            name='qty',
        ),
        migrations.AddField(
            model_name='tenderslist',
            name='lotsInfo',
            field=models.TextField(null=True),
        ),
    ]
